version: "3.8"

services:
  mysql-service:
    image: mysql:8
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
      - MYSQL_DATABASE=ems
    volumes:
      - "./env/mysql/conf.d:/etc/mysql/conf.d:ro"
      - "./env/mysql/data:/var/lib/mysql:rw"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge