# -*- mode: ruby -*-
# vi: set ft=ruby :

## configuration variables ##
# max number of worker nodes
N = 3
# each of components to install 
k8s_V = '1.24.8' # Kubernetes
docker_V = '20.10.21-3.el9' # Docker
ctrd_V = '1.6.12-3.1.el9'# Containerd
## /configuration variables ##

Vagrant.configure("2") do |config|

  #=============#
  # Master Node #
  #=============#
  config.vm.define "master" do |cfg|
    cfg.vm.box = "marcinbojko/rockylinux9_arm64"
    cfg.vm.provider "parallels" do |prl|
      prl.name = "master-k8s-#{k8s_V[0..5]}"
      prl.cpus = 2
      prl.memory = 4096
      prl.linked_clone = false
      prl.update_guest_tools = false
      prl.check_guest_tools = false
    end
    cfg.vm.host_name = "master.local"
    cfg.vm.network "private_network", ip: "192.168.100.10"
    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "k8s_env_build.sh", args: N
    cfg.vm.provision "shell", path: "k8s_pkg_cfg.sh", args: [k8s_V, docker_V, ctrd_V]
    cfg.vm.provision "shell", path: "master_node.sh"
  end

  # #==============#
  # # Worker Nodes #
  # #==============#
  # (1..N).each do |i|
  #   config.vm.define "worker#{i}" do |cfg|
  #     cfg.vm.box = "marcinbojko/rockylinux9_arm64"
  #     cfg.vm.provider "parallels" do |prl|
  #       prl.name = "worker#{i}-k8s-#{k8s_V[0..5]}"
  #       prl.cpus = 1
  #       prl.memory = 2048
  #       prl.linked_clone = false
  #       prl.update_guest_tools = false
  #       prl.check_guest_tools = false
  #     end
  #     cfg.vm.host_name = "worker#{i}.local"
  #     cfg.vm.network "private_network", ip: "192.168.100.10#{i}"
  #     cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
  #     cfg.vm.synced_folder "../data", "/vagrant", disabled: true
  #     cfg.vm.provision "shell", path: "k8s_env_build.sh", args: N
  #     cfg.vm.provision "shell", path: "k8s_pkg_cfg.sh", args: [k8s_V, docker_V, ctrd_V]
  #     cfg.vm.provision "shell", path: "work_nodes.sh"
  #   end
  # end

end
