# -*- mode: ruby -*-
# vi: set ft-ruby :

Vagrant.configure("2") do |config|
  NodeCount = 3
  KubeVer = "1.24.2-00"

  # master node
  config.vm.define "master" do |master|
    master.vm.box = "bento/ubuntu-20.04-arm64"
    master.vm.box_version = "202112.19.0"
    master.vm.provider "parallels" do |prl|
      prl.linked_clone = false
      prl.cpus = 2
      prl.memory = 4096
    end
    master.vm.hostname = "master-node"
    master.vm.network "private_network", ip: "192.168.100.100"
    master.vm.network "forwarded_port", guest: 22, host: 60100, auto_correct: true, id: "ssh"
    master.vm.synced_folder "../data", "/vagrant", disabled: true
    master.vm.provision "shell", path: "scripts/config.sh", args: NodeCount
    master.vm.provision "shell", path: "scripts/install_pkg.sh", args: [KubeVer, "Main"]
    master.vm.provision "shell", path: "scripts/master_node.sh"
  end

  # worker nodes
  (1..NodeCount).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "bento/ubuntu-20.04-arm64"
      worker.vm.box_version = "202112.19.0"
      worker.vm.provider "parallels" do |prl|
        prl.linked_clone = false
        prl.cpus = 2
        prl.memory = 4096
      end
      worker.vm.hostname = "worker-node#{i}"
      worker.vm.network "private_network", ip: "192.168.100.#{i + 100}"
      worker.vm.network "forwarded_port", guest: 22, host: "60#{i + 100}", auto_correct: true, id: "ssh"
      worker.vm.synced_folder "../data", "/vagrant", disabled: true
      worker.vm.provision "shell", path: "scripts/config.sh", args: NodeCount
      worker.vm.provision "shell", path: "scripts/install_pkg.sh", args: KubeVer
      worker.vm.provision "shell", path: "scripts/worker_node.sh"
    end
  end
   
end
