version: "3.8"

services:
  mysql-service:
    image: mysql:8
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
      - MYSQL_DATABASE=testdb
    volumes:
      - "./env/mysql/conf.d:/etc/mysql/conf.d:ro"
      - "./env/mysql/data:/var/lib/mysql:rw"
    networks:
      - local-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  local-network:
    driver: bridge